image:
  file: Dockerfile

tasks:
  -  before: mkdir android \ &&
             touch logs.txt
             
             
     command: echo "ls -la"          2>&1 | tee  logs.txt \ &&     
              ls -la                 2>&1 | tee  logs.txt \ &&  
              echo                   2>&1 | tee  logs.txt \ &&    
              echo "javac -version"  2>&1 | tee  logs.txt \ &&       
              javac -version         2>&1 | tee  logs.txt  

    
    
 
