image:
  file: Dockerfile

tasks:
  -  before: mkdir android \ &&
             touch logs.txt
             
             
     command: echo "ls -la" >>  logs.txt \ &&     
              ls -la >> logs.txt \ &&  
              echo  >>  logs.txt \ &&    
              echo "javac -version" >>  logs.txt \ &&       
              javac -version >> logs.txt  

    
    
 
