image:
  file: Dockerfile

tasks:
  -  before: touch logs.txt \ &&
             mkdir myTempDir
             
             
     command: echo "ls -la"  >> logs.txt \ &&    
              ls -la         >> logs.txt \ &&          
              echo           >> logs.txt \ &&       
              
              echo "pwd"     >> logs.txt \ &&          
              pwd            >> logs.txt \ &&     
              echo           >> logs.txt \ &&     
              
              echo "cd .."   >> logs.txt \ &&          
              cd ..          >> logs.txt \ &&     
              echo           >> logs.txt \ &&       
              
              echo "pwd"     >> logs.txt \ &&           
              pwd            >> logs.txt \ &&     
              echo           >> logs.txt 
 
