image:
  file: Dockerfile

tasks:
  -  before: mkdir android \ &&
             touch logs.txt
             
             
     command: echo "ls -la"| tee  logs.txt \ &&     
              ls -la | tee  logs.txt \ &&  
              echo  | tee   logs.txt \ &&    
              echo "javac -version" | tee   logs.txt \ &&       
              javac -version | tee  logs.txt  

    
    
 
