image:
  file: Dockerfile

tasks:
  -  before: mkdir /other \ &&
             mkdir android
             
             
     command: echo "ls"      >> logs.txt \ &&    
              ls             >> logs.txt \ &&          
              echo           >> logs.txt \ &&       
              
              echo "pwd"     >> logs.txt \ &&          
              pwd            >> logs.txt \ &&     
              echo           >> logs.txt \ &&     
              
              echo "cd .."   >> logs.txt \ &&          
              cd ..          >> logs.txt \ &&     
              echo           >> logs.txt \ &&       
              
              echo "pwd"     >> logs.txt \ &&           
              pwd            >> logs.txt \ &&     
              echo           >> logs.txt 
 
