image:
  file: Dockerfile

tasks:
  -  init: touch logs.txt  &&
           mkdir android
             
             
     command: echo "ls -la"           &>> /workspace/my-gitpod-android/logs.txt  &&    
              ls -la                  &>> /workspace/my-gitpod-android/logs.txt  &&        
              echo                    &>> /workspace/my-gitpod-android/logs.txt  &&         
              
              echo "pwd"              &>> /workspace/my-gitpod-android/logs.txt  &&           
              pwd                     &>> /workspace/my-gitpod-android/logs.txt  &&      
              echo                    &>> /workspace/my-gitpod-android/logs.txt  &&      
              
              echo "java -version"    &>> /workspace/my-gitpod-android/logs.txt  &&           
              java -version           &>>  /workspace/my-gitpod-android/logs.txt  &&     
              echo                    &>> /workspace/my-gitpod-android/logs.txt  &&      
                            
              echo "wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip"    &>> /workspace/my-gitpod-android/logs.txt  &&           
              wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip           &>>  /workspace/my-gitpod-android/logs.txt  &&     
              echo                                                                                &>> /workspace/my-gitpod-android/logs.txt  &&   
           
              echo "unzip sdk-tools-linux-4333796.zip -d android"    &>> /workspace/my-gitpod-android/logs.txt  &&           
              unzip sdk-tools-linux-4333796.zip -d android           &>>  /workspace/my-gitpod-android/logs.txt  &&     
              echo                    &>> /workspace/my-gitpod-android/logs.txt  &&  
             
              echo "rm sdk-tools-linux-4333796.zip"    &>> /workspace/my-gitpod-android/logs.txt  &&           
              rm sdk-tools-linux-4333796.zip           &>>  /workspace/my-gitpod-android/logs.txt  &&     
              echo                    &>> /workspace/my-gitpod-android/logs.txt  &&       
              
              echo "javac -version"   &>> /workspace/my-gitpod-android/logs.txt  &&             
              javac -version          &>> /workspace/my-gitpod-android/logs.txt  &&      
              echo                    &>> /workspace/my-gitpod-android/logs.txt  
              
              
 
