image:
  file: Dockerfile

tasks:
  -  init: touch logs.txt  &&
           mkdir android   &&
           mkdir cordova
             
             
     command: echo "ls -la"           &>> /workspace/my-gitpod-android/logs.txt  &&    
              ls -la                  &>> /workspace/my-gitpod-android/logs.txt  &&        
              echo                    &>> /workspace/my-gitpod-android/logs.txt  &&         
              
              echo "pwd"              &>> /workspace/my-gitpod-android/logs.txt  &&           
              pwd                     &>> /workspace/my-gitpod-android/logs.txt  &&      
              echo                    &>> /workspace/my-gitpod-android/logs.txt  &&      
              
              echo "java -version"    &>> /workspace/my-gitpod-android/logs.txt  &&           
              java -version           &>> /workspace/my-gitpod-android/logs.txt  &&     
              echo                    &>> /workspace/my-gitpod-android/logs.txt  &&      
                            
              echo "wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip"    &>> /workspace/my-gitpod-android/logs.txt  &&           
              wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip           &>>  /workspace/my-gitpod-android/logs.txt  &&     
              echo                                                                                &>> /workspace/my-gitpod-android/logs.txt  &&   
           
              echo "unzip sdk-tools-linux-4333796.zip -d android"    &>> /workspace/my-gitpod-android/logs.txt  &&           
              unzip sdk-tools-linux-4333796.zip -d android                                                      &&     
              echo                                                   &>> /workspace/my-gitpod-android/logs.txt  &&  
             
              echo "rm sdk-tools-linux-4333796.zip"    &>> /workspace/my-gitpod-android/logs.txt  &&           
              rm sdk-tools-linux-4333796.zip           &>>  /workspace/my-gitpod-android/logs.txt  &&     
              echo                                     &>> /workspace/my-gitpod-android/logs.txt  &&       
              

              
              echo "./android/tools/bin/sdkmanager --list"    &>> /workspace/my-gitpod-android/logs.txt  &&           
              ./android/tools/bin/sdkmanager --list           &>> /workspace/my-gitpod-android/logs.txt  &&     
              echo                                            &>> /workspace/my-gitpod-android/logs.txt  &&                  
              
              
     
              echo 'yes | ./android/tools/bin/sdkmanager "platform-tools" "platforms;android-28"'    &>> /workspace/my-gitpod-android/logs.txt  &&           
              yes | ./android/tools/bin/sdkmanager "platform-tools" "platforms;android-28"           &>> /workspace/my-gitpod-android/logs.txt  &&     
              echo                                                                                   &>> /workspace/my-gitpod-android/logs.txt  &&            
              
              
              
              
              echo 'export ANDROID_SDK_ROOT="/workspace/my-gitpod-android/android/"'    &>> /workspace/my-gitpod-android/logs.txt  &&           
              export ANDROID_SDK_ROOT="/workspace/my-gitpod-android/android/"           &>> /workspace/my-gitpod-android/logs.txt  &&     
              echo  $ANDROID_SDK_ROOT                                                   &>> /workspace/my-gitpod-android/logs.txt  &&      
              echo                                                                      &>> /workspace/my-gitpod-android/logs.txt  &&      
              
              
             
              echo 'export PATH="${PATH}:${ANDROID_SDK_ROOT}tools/:${ANDROID_SDK_ROOT}platform-tools/"'    &>> /workspace/my-gitpod-android/logs.txt  &&           
              export PATH="${PATH}:${ANDROID_SDK_ROOT}tools/:${ANDROID_SDK_ROOT}platform-tools/"           &>> /workspace/my-gitpod-android/logs.txt  &&     
              echo                                                                                         &>> /workspace/my-gitpod-android/logs.txt  &&       
              
              
              
            
              
              echo "npm install   -p /workspace/my-gitpod-android/cordova cordova"    &>> /workspace/my-gitpod-android/logs.txt  &&           
              npm install   -p /workspace/my-gitpod-android/cordova cordova           &>> /workspace/my-gitpod-android/logs.txt  &&     
              echo                                                                    &>> /workspace/my-gitpod-android/logs.txt  &&     
              
         
         
       
              echo 'export PATH="${PATH}:$/workspace/my-gitpod-android/cordova/node_modules/:/workspace/my-gitpod-android/cordova/node_modules/cordova/bin:/workspace/my-gitpod-android/cordova/node_modules/qrcode/bin"'    &>> /workspace/my-gitpod-android/logs.txt  &&           
              export PATH="${PATH}:$/workspace/my-gitpod-android/cordova/node_modules/:/workspace/my-gitpod-android/cordova/node_modules/cordova/bin:/workspace/my-gitpod-android/cordova/node_modules/qrcode/bin"           &>> /workspace/my-gitpod-android/logs.txt  &&     
              echo  $PATH                  &>> /workspace/my-gitpod-android/logs.txt  &&     
              echo                         &>> /workspace/my-gitpod-android/logs.txt  &&            
         
         
         
         
              
              echo "javac -version"   &>> /workspace/my-gitpod-android/logs.txt  &&             
              javac -version          &>> /workspace/my-gitpod-android/logs.txt  &&      
              echo                    &>> /workspace/my-gitpod-android/logs.txt  
              
              
 
