image:
  file: Dockerfile

tasks:
  -  init: touch logs.txt  &&
             mkdir myTempDir
             
             
     command: echo "ls -la"  >> /workspace/my-gitpod-android/logs.txt  &&    
              ls -la         >> /workspace/my-gitpod-android/logs.txt  &&        
              echo           >> /workspace/my-gitpod-android/logs.txt  &&         
              
              echo "pwd"     >> /workspace/my-gitpod-android/logs.txt  &&           
              pwd            >> /workspace/my-gitpod-android/logs.txt  &&      
              echo           >> /workspace/my-gitpod-android/logs.txt  &&      
              
              echo "cd .."   >> /workspace/my-gitpod-android/logs.txt  &&           
              cd ..          >> /workspace/my-gitpod-android/logs.txt  &&     
              echo           >> /workspace/my-gitpod-android/logs.txt  &&      
              
              echo "pwd"     >> /workspace/my-gitpod-android/logs.txt  &&             
              pwd            >> /workspace/my-gitpod-android/logs.txt  &&      
              echo           >> /workspace/my-gitpod-android/logs.txt  
 
