image:
  file: Dockerfile

tasks:
  -  init: touch logs.txt  &&
           mkdir android
             
             
     command: echo "ls -la"  >> /workspace/my-gitpod-android/logs.txt  &&    
              ls -la         >> /workspace/my-gitpod-android/logs.txt  &&        
              echo           >> /workspace/my-gitpod-android/logs.txt  &&         
              
              echo "pwd"     >> /workspace/my-gitpod-android/logs.txt  &&           
              pwd            >> /workspace/my-gitpod-android/logs.txt  &&      
              echo           >> /workspace/my-gitpod-android/logs.txt  &&      
              
              echo "java -version"   >> /workspace/my-gitpod-android/logs.txt  &&           
              java -version         |& tee -a  /workspace/my-gitpod-android/logs.txt  &&     
              echo                   >> /workspace/my-gitpod-android/logs.txt  &&      
                            
              
              echo "javac -version"  |& tee -a  /workspace/my-gitpod-android/logs.txt  &&             
              javac -version         |& tee -a  /workspace/my-gitpod-android/logs.txt  &&      
              echo                   |& tee -a  /workspace/my-gitpod-android/logs.txt  
              
              
 
